services:
  epoch:
    image: epoch:latest
    build:
      context: ".."
      dockerfile: docker/Dockerfile
    # Example Volume Mapping
    # volumes:
    #   - ./i2:/EP/Epoch/InputData
    #   - ./o2:/EP/Epoch/OutputData
