services:
  demonstrator:
    image: epoch_demonstrator:latest
    build:
      context: "../.."
      dockerfile: epoch_server/docker/Dockerfile
    ports:
      - "8763:8763"
    network_mode: "host"
