[tool.ruff]
extend-include = ["*.ipynb"]
line-length = 128

[tool.ruff.lint]
select = ["E", "W", "F", "B", "I", "A", "C4"]

[tool.pytest.ini_options]
markers = [
    "requires_epoch: Mark tests as requiring Epoch, and disable if we can't find it (deselect with '-m \"not requires_epoch\"')",
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]